spring:
  datasource:
    username: myuser
    password: secret
    url: jdbc:postgresql://localhost:5432/mydatabase
  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug